#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Appointments/Appointments.csproj", "Appointments/"]
RUN dotnet restore "Appointments/Appointments.csproj"
COPY . .
WORKDIR "/src/Appointments"
RUN dotnet build "Appointments.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Appointments.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Appointments.dll","--urls", "http://0.0.0.0:5001"]